# Fantasy Premier League API

Exploring the Fantasy Premier League API to view the data available.

Contains information on players, teams, gameweeks, fixtures and more.

In [49]:
# imports
import requests
import pandas as pd

# Bootstrap Static Endpoint

In [50]:
# base url for FPL API
url = 'https://fantasy.premierleague.com/api/'

# get request for boostrap-static endpoint
r = requests.get(url + 'bootstrap-static/').json()

In [51]:
# return keys of the dictionary from r
r.keys()

dict_keys(['chips', 'events', 'game_settings', 'game_config', 'phases', 'teams', 'total_players', 'element_stats', 'element_types', 'elements'])

In [52]:
# lists chips available to FPL managers and the windows (GWs) they can be used
chips_df = pd.DataFrame(r['chips'])
chips_df

,id,name,number,start_event,stop_event,chip_type,overrides
0,1,wildcard,1,2,19,transfer,"{'rules': {}, 'scoring': {}, 'element_types': ..."
1,2,wildcard,1,20,38,transfer,"{'rules': {}, 'scoring': {}, 'element_types': ..."
2,3,freehit,1,2,19,transfer,"{'rules': {}, 'scoring': {}, 'element_types': ..."
3,4,bboost,1,1,19,team,"{'rules': {}, 'scoring': {}, 'element_types': ..."
4,5,3xc,1,1,19,team,"{'rules': {}, 'scoring': {}, 'element_types': ..."
5,6,freehit,1,20,38,transfer,"{'rules': {}, 'scoring': {}, 'element_types': ..."
6,7,bboost,1,20,38,team,"{'rules': {}, 'scoring': {}, 'element_types': ..."
7,8,3xc,1,20,38,team,"{'rules': {}, 'scoring': {}, 'element_types': ..."

In [53]:
# list of all gws, deadlines and stats --> events = GWs
events_df = pd.DataFrame(r['events'])
events_df.head()

,id,name,deadline_time,release_time,average_entry_score,finished,data_checked,highest_scoring_entry,deadline_time_epoch,deadline_time_game_offset,...,ranked_count,overrides,chip_plays,most_selected,most_transferred_in,top_element,top_element_info,transfers_made,most_captained,most_vice_captained
0,1,Gameweek 1,2025-08-15T17:30:00Z,None,54,True,True,3772644.0,1755279000,0,...,9469118,"{'rules': {}, 'scoring': {}, 'element_types': ...","[{'chip_name': 'bboost', 'num_played': 342779}...",235.0,1.0,531.0,"{'id': 531, 'points': 17}",0,381.0,235.0
1,2,Gameweek 2,2025-08-22T17:30:00Z,None,51,True,True,2963810.0,1755883800,0,...,10752422,"{'rules': {}, 'scoring': {}, 'element_types': ...","[{'chip_name': 'bboost', 'num_played': 206501}...",235.0,427.0,8.0,"{'id': 8, 'points': 24}",18178809,381.0,235.0
2,3,Gameweek 3,2025-08-30T10:00:00Z,None,48,True,True,4374360.0,1756548000,0,...,11304791,"{'rules': {}, 'scoring': {}, 'element_types': ...","[{'chip_name': 'bboost', 'num_played': 181694}...",249.0,82.0,260.0,"{'id': 260, 'points': 15}",27802596,430.0,381.0
3,4,Gameweek 4,2025-09-13T10:00:00Z,None,63,True,True,7997042.0,1757757600,0,...,11641518,"{'rules': {}, 'scoring': {}, 'element_types': ...","[{'chip_name': 'bboost', 'num_played': 151177}...",249.0,419.0,26.0,"{'id': 26, 'points': 16}",27408255,381.0,249.0
4,5,Gameweek 5,2025-09-20T10:00:00Z,None,42,True,True,9985225.0,1758362400,0,...,11803614,"{'rules': {}, 'scoring': {}, 'element_types': ...","[{'chip_name': 'bboost', 'num_played': 231274}...",249.0,82.0,660.0,"{'id': 660, 'points': 15}",16533109,381.0,249.0

In [54]:
# which gameweeks are in which months
phases_df = pd.DataFrame(r['phases'])
phases_df

    id       name  start_event  stop_event  highest_score
0    1    Overall            1          38           2506
1    2     August            1           3            272
2    3  September            4           6            283
3    4    October            7           9            282
4    5   November           10          13            336
5    6   December           14          19            508
6    7    January           20          24            375
7    8   February           25          28            370
8    9      March           29          31            275
9   10      April           32          34            326
10  11        May           35          38            298

In [55]:
# all 20 Premier League teams + stats
teams_df = pd.DataFrame(r['teams'])
teams_df

,code,draw,form,id,loss,name,played,points,position,short_name,...,unavailable,win,link_url,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,1,ARS,...,False,0,,1305,1355,1340,1390,1270,1320,1
1,7,0,None,2,0,Aston Villa,0,0,4,AVL,...,False,0,,1135,1230,1120,1210,1150,1250,2
2,90,0,None,3,0,Burnley,0,0,19,BUR,...,False,0,,975,1045,910,1050,1040,1040,43
3,91,0,None,4,0,Bournemouth,0,0,6,BOU,...,False,0,,1150,1235,1060,1230,1240,1240,127
4,94,0,None,5,0,Brentford,0,0,9,BRE,...,False,0,,1135,1215,1120,1160,1150,1270,130
5,36,0,None,6,0,Brighton,0,0,7,BHA,...,False,0,,1170,1250,1140,1220,1200,1280,131
6,8,0,None,7,0,Chelsea,0,0,8,CHE,...,False,0,,1190,1195,1130,1140,1250,1250,4
7,31,0,None,8,0,Crystal Palace,0,0,15,CRY,...,False,0,,1160,1185,1150,1200,1170,1170,6
8,11,0,None,9,0,Everton,0,0,12,EVE,...,False,0,,1135,1160,1130,1150,1140,1170,7
9,54,0,None,10,0,Fulham,0,0,13,FUL,...,False,0,,1105,1200,1090,1170,1120,1230,34
10,2,0,None,11,0,Leeds,0,0,14,LEE,...,False,0,,1100,1205,1050,1160,1150,1250,9
11,14,0,None,12,0,Liverpool,0,0,5,LIV,...,False,0,,1180,1250,1120,1200,1240,1300,10
12,43,0,None,13,0,Man City,0,0,2,MCI,...,False,0,,1265,1355,1220,1310,1310,1400,11
13,1,0,None,14,0,Man Utd,0,0,3,MUN,...,False,0,,1180,1250,1120,1190,1240,1310,12
14,4,0,None,15,0,Newcastle,0,0,11,NEW,...,False,0,,1120,1205,1130,1120,1110,1290,23
15,17,0,None,16,0,Nott'm Forest,0,0,16,NFO,...,False,0,,1125,1165,1130,1160,1120,1170,15
16,56,0,None,17,0,Sunderland,0,0,10,SUN,...,False,0,,1055,1150,1070,1170,1040,1130,29
17,6,0,None,18,0,Spurs,0,0,17,TOT,...,False,0,,1120,1120,1090,1090,1150,1150,21
18,21,0,None,19,0,West Ham,0,0,18,WHU,...,False,0,,1095,1130,1060,1080,1130,1180,25
19,39,0,None,20,0,Wolves,0,0,20,WOL,...,False,0,,975,1060,950,1050,1000,1070,38

In [56]:
# total count of FPL Managers
total_players = r['total_players']
print(total_players)

13104710

In [57]:
# name and label of element stats
element_stats_df = pd.DataFrame(r['element_stats'])
element_stats_df

                                   label                             name
0                         Minutes played                          minutes
1                           Goals scored                     goals_scored
2                                Assists                          assists
3                           Clean sheets                     clean_sheets
4                         Goals conceded                   goals_conceded
5                              Own goals                        own_goals
6                        Penalties saved                  penalties_saved
7                       Penalties missed                 penalties_missed
8                           Yellow cards                     yellow_cards
9                              Red cards                        red_cards
10                                 Saves                            saves
11                                 Bonus                            bonus
12                   Bonus Points System                              bps
13                             Influence                        influence
14                            Creativity                       creativity
15                                Threat                           threat
16                             ICT Index                        ict_index
17  Clearances, blocks and interceptions  clearances_blocks_interceptions
18                            Recoveries                       recoveries
19                               Tackles                          tackles
20                Defensive Contribution           defensive_contribution
21                       Game(s) Started                           starts
22                        Expected Goals                   expected_goals
23                      Expected Assists                 expected_assists
24            Expected Goal Involvements       expected_goal_involvements
25               Expected Goals Conceded          expected_goals_conceded

In [58]:
# types of elements e.g. MID, DEF
# contains the upper and lower bounds of position types for team selection
element_types_df = pd.DataFrame(r['element_types'])
element_types_df

,id,plural_name,plural_name_short,singular_name,singular_name_short,squad_select,squad_min_select,squad_max_select,squad_min_play,squad_max_play,ui_shirt_specific,sub_positions_locked,element_count
0,1,Goalkeepers,GKP,Goalkeeper,GKP,2,None,None,1,1,True,[12],97
1,2,Defenders,DEF,Defender,DEF,5,None,None,3,5,False,[],270
2,3,Midfielders,MID,Midfielder,MID,5,None,None,2,5,False,[],379
3,4,Forwards,FWD,Forward,FWD,3,None,None,1,3,False,[],94

In [59]:
# list of all players and stats (summed to current gw when run)
elements_df = pd.DataFrame(r['elements'])
elements_df

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,price_change_percent,...,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90
0,True,True,NaN,NaN,154561,1,-1,7,-7,0,...,1,2,1,37,3,6,1,1.00,0.51,0.00
1,True,True,NaN,NaN,109745,0,0,-5,5,0,...,44,460,55,590,67,292,37,0.00,0.00,0.00
2,True,False,0.0,0.0,463748,0,0,0,0,0,...,54,479,65,607,76,382,54,0.00,0.00,0.00
3,True,True,NaN,NaN,551221,0,0,-1,1,0,...,90,445,48,579,61,373,53,0.00,0.00,0.00
4,True,True,100.0,100.0,226597,0,0,13,-13,0,...,1,3,1,3,1,4,1,1.00,0.60,9.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,True,True,NaN,NaN,685628,0,0,0,0,0,...,329,709,290,781,336,725,301,0.00,0.00,0.00
836,True,True,100.0,100.0,209041,0,0,-4,4,0,...,247,328,140,441,193,709,289,1.38,0.23,6.43
837,True,True,NaN,NaN,155511,-1,1,-4,4,0,...,49,184,26,276,29,577,79,1.10,0.25,3.03
838,True,True,NaN,NaN,491460,0,0,0,0,0,...,58,484,69,612,80,780,91,0.00,0.00,0.00
839,True,True,NaN,NaN,627888,0,0,0,0,0,...,68,524,79,646,89,785,92,0.00,0.00,0.00

# Element Summary Endpoint

In [60]:
# get player e.g. player 1
# element-summary/{{player_id}}/ --> replace player_id with value
r = requests.get(url + 'element-summary/1/').json()
r.keys()

dict_keys(['fixtures', 'history', 'history_past'])

In [61]:
# players upcoming fixtures for live season
element_fix_df = pd.DataFrame(r['fixtures'])
element_fix_df

,id,code,team_h,team_h_score,team_a,team_a_score,event,finished,minutes,provisional_start_time,kickoff_time,event_name,is_home,difficulty
0,373,2562267,8,None,1,None,38,False,0,False,2026-05-24T15:00:00Z,Gameweek 38,False,3

In [62]:
# player stats of previous games in current season
element_history_df = pd.DataFrame(r['history'])
element_history_df.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,...,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out
0,1,9,14,10,False,2025-08-17T15:30:00Z,0,1,1,False,...,1,0.00,0.00,0.00,1.52,55,0,1531911,0,0
1,1,11,11,6,True,2025-08-23T16:30:00Z,5,0,2,False,...,1,0.00,0.00,0.00,0.17,55,218659,2284634,277339,58680
2,1,25,12,2,False,2025-08-31T15:30:00Z,1,0,3,False,...,1,0.00,0.02,0.02,0.52,55,-12311,2406964,146739,159050
3,1,31,16,6,True,2025-09-13T11:30:00Z,3,0,4,False,...,1,0.00,0.00,0.00,0.20,55,171289,2765759,289041,117752
4,1,41,13,2,True,2025-09-21T15:30:00Z,1,1,5,False,...,1,0.00,0.01,0.01,0.89,55,-9786,2762632,98100,107886

In [63]:
# players stats from previous seasons (summary)
element_history_past_df = pd.DataFrame(r['history_past'])
element_history_past_df

,season_name,element_code,start_cost,end_cost,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,...,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded
0,2021/22,154561,45,44,95,2160,0,0,8,27,...,60.1,0,0,0,0,0,0.00,0.00,0.00,0.00
1,2022/23,154561,45,48,166,3420,0,0,12,46,...,117.3,0,0,0,0,38,0.11,0.12,0.23,50.12
2,2023/24,154561,50,53,135,2880,0,0,16,24,...,41.1,0,0,0,0,32,0.00,0.04,0.04,22.51
3,2024/25,154561,55,56,142,3420,0,0,13,34,...,76.7,0,0,0,0,38,0.00,0.03,0.03,35.03

# Gameweek Fixtures Endpoint

In [64]:
# fixtures/?event={{gw_id}} --> replace gw_id with value
# event = 1 is the first gw of the season
r = requests.get(url + 'fixtures/?event=1').json()
gw_fixture_df = pd.DataFrame(r)
gw_fixture_df.head()

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2561895,1,True,True,1,2025-08-15T19:00:00Z,90,False,True,4,2,12,4,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,4,124791
1,2561896,1,True,True,2,2025-08-16T11:30:00Z,90,False,True,15,0,2,0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,4,124792
2,2561897,1,True,True,3,2025-08-16T14:00:00Z,90,False,True,10,1,6,1,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,4,124793
3,2561900,1,True,True,6,2025-08-16T14:00:00Z,90,False,True,3,0,18,3,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",1,3,124796
4,2561899,1,True,True,5,2025-08-16T14:00:00Z,90,False,True,19,0,17,3,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,3,124795

# Gameweek Live Endpoint

In [65]:
# /{{gw_id}}/live/ --> replace gw_id with value
# list of elements, players live gw performance
r = requests.get(url + 'event/1/live/').json()
gw_live_df = pd.DataFrame(r)
gw_live_df

                                              elements
0    {'id': 1, 'stats': {'minutes': 90, 'goals_scor...
1    {'id': 2, 'stats': {'minutes': 0, 'goals_score...
2    {'id': 3, 'stats': {'minutes': 0, 'goals_score...
3    {'id': 4, 'stats': {'minutes': 0, 'goals_score...
4    {'id': 5, 'stats': {'minutes': 90, 'goals_scor...
..                                                 ...
685  {'id': 686, 'stats': {'minutes': 0, 'goals_sco...
686  {'id': 687, 'stats': {'minutes': 0, 'goals_sco...
687  {'id': 688, 'stats': {'minutes': 0, 'goals_sco...
688  {'id': 689, 'stats': {'minutes': 0, 'goals_sco...
689  {'id': 690, 'stats': {'minutes': 0, 'goals_sco...

[690 rows x 1 columns]

# Save dataframes to csv

Viewing the data in the FPL API is useful, but we may want to save it for later use.

In [66]:
# save elements dataframe to csv, which contains all players and all stats, for viewing
elements_df.to_csv(r'..\data\fromAPI\elements.csv', index=False)

In [67]:
# save all 20 Premier League teams and stats to csv
teams_df.to_csv(r'..\data\fromAPI\teams.csv', index=False)

# Merge elements and teams

merging these two dataframes allows us to know which player belongs to which team.

In [68]:
# find columns that exist in both files
shared_columns = set(elements_df.columns).intersection(set(teams_df.columns))

# remove the column we plan to merge on
problem_columns = shared_columns - {'team_id'}

# print columns that may cause _x and _y after merging
print(problem_columns)

{'code', 'form', 'id'}

In [69]:
# Rename some overlapping columns to differentiate original source
elements_df = elements_df.rename(columns={
    'id': 'player_id',
    'team': 'team_id',
    'code': 'player_code',
    'form': 'player_form'
})

teams_df = teams_df.rename(columns={
    'id': 'team_id',
    'form': 'team_form',
    'name': 'team_name'
})

# we drop code as elements already has team_code, which is the same thing
teams_df = teams_df.drop(columns = ['code'])

# merge players to teams using the team ID
elements_teams = elements_df.merge(
    teams_df,
    on='team_id',
    how='left'
)

with pd.option_context('display.max_rows', None):
    print(elements_teams.loc[0])

# save as backup/for viewing
elements_teams.to_csv(r'..\data\fromAPI\elements_teams.csv', index=False)

can_transact                                   True
can_select                                     True
chance_of_playing_next_round                    NaN
chance_of_playing_this_round                    NaN
player_code                                  154561
cost_change_event                                 1
cost_change_event_fall                           -1
cost_change_start                                 7
cost_change_start_fall                           -7
price_change_percent                              0
dreamteam_count                                   2
element_type                                      1
ep_next                                         8.8
ep_this                                         9.3
event_points                                      6
first_name                                    David
player_form                                     7.8
player_id                                         1
in_dreamteam                                   True
news
news_added                                      NaN
now_cost                                         62
photo                                    154561.jpg
points_per_game                                 4.4
removed                                       False
second_name                             Raya Martín
selected_by_percent                            36.5
special                                       False
squad_number                                   None
status                                            a
team_id                                           1
team_code                                         3
total_points                                    162
transfers_in                                4881658
transfers_in_event                            39782
transfers_out                               2951580
transfers_out_event                           16695
value_form                                      1.3
value_season                                   26.1
web_name                                       Raya
known_name
region                                        200.0
team_join_date                           2024-07-04
birth_date                               1995-09-15
has_temporary_code                            False
opta_code                                   p154561
minutes                                        3330
goals_scored                                      0
assists                                           0
clean_sheets                                     19
goals_conceded                                   26
own_goals                                         0
penalties_saved                                   0
penalties_missed                                  0
yellow_cards                                      1
red_cards                                         0
saves                                            60
bonus                                            11
bps                                             633
influence                                     541.6
creativity                                     33.5
threat                                          0.0
ict_index                                      57.5
clearances_blocks_interceptions                  37
recoveries                                      304
tackles                                           1
defensive_contribution                            0
starts                                           37
expected_goals                                 0.00
expected_assists                               0.07
expected_goal_involvements                     0.07
expected_goals_conceded                       27.56
corners_and_indirect_freekicks_order            NaN
corners_and_indirect_freekicks_text
direct_freekicks_order                          NaN
direct_freekicks_text
penalties_order                                 NaN
penalties_text
scout_risks                                      []
scout_news_link
influence_rank                                  105
influence_rank_type                              17
creativity_rank                                 390
creativity_rank_type                              3
threat_rank                                     832
threat_rank_type                                 97
ict_index_rank                                  272
ict_index_rank_type                              17
expected_goals_per_90                           0.0
saves_per_90                                   1.62
expected_assists_per_90                         0.0
expected_goal_involvements_per_90               0.0
expected_goals_conceded_per_90                 0.74
goals_conceded_per_90                           0.7
now_cost_rank                                    72
now_cost_rank_type                                1
form_rank                                         2
form_rank_type                                    1
points_per_game_rank                             37
points_per_game_rank_type                         3
selected_rank                                     6
selected_rank_type                                1
starts_per_90                                   1.0
clean_sheets_per_90                            0.51
defensive_contribution_per_90                   0.0
draw                                              0
team_form                                      None
loss                                              0
team_name                                   Arsenal
played                                            0
points                                            0
position                                          1
short_name                                      ARS
strength                                          5
team_division                                  None
unavailable                                   False
win                                               0
link_url
strength_overall_home                          1305
strength_overall_away                          1355
strength_attack_home                           1340
strength_attack_away                           1390
strength_defence_home                          1270
strength_defence_away                          1320
pulse_id                                          1
Name: 0, dtype: object